# Generated by Django 5.1.3 on 2024-12-02 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('condo', 'Condo'), ('office', 'Office'), ('studio', 'Studio'), ('store', 'Store')], max_length=50)),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('rental', 'Rental')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent')], max_length=10)),
                ('cover_image', models.ImageField(upload_to='property_images/')),
                ('other_images', models.JSONField()),
                ('features', models.JSONField()),
                ('amenities', models.JSONField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
