# Generated by Django 5.1.3 on 2024-12-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_property_other_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.TextField(default='[]'),
        ),
    ]
