# Generated by Django 5.1.3 on 2024-12-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='https://83f1-102-218-124-142.ngrok-free.app'),
        ),
    ]
